// @ts-check
import { existsSync, readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import cloudflare from '@astrojs/cloudflare';

// `src/wiki-nav.json` is generated by `scripts/sync-wiki.mjs` from the wiki's
// `_Sidebar.md` (or an alphabetical fallback). Falls back to the starter
// sidebar when the wiki has never been synced yet.
const navPath = new URL('./src/wiki-nav.json', import.meta.url);
/** @typedef {{label: string, slug: string} | {label: string, items: NavEntry[]}} NavEntry */
/** @param {NavEntry[]} entries @returns {any[]} */
function toStarlightSidebar(entries) {
	return entries.map((entry) =>
		'items' in entry ? { label: entry.label, items: toStarlightSidebar(entry.items) } : entry,
	);
}

/** @param {NavEntry[]} entries @returns {string | undefined} */
function firstSlug(entries) {
	for (const entry of entries) {
		if ('slug' in entry) return entry.slug;
		if ('items' in entry) {
			const found = firstSlug(entry.items);
			if (found) return found;
		}
	}
	return undefined;
}

/** @type {NavEntry[]} */
const parsedNav = existsSync(navPath) ? JSON.parse(readFileSync(navPath, 'utf-8')) : [];
const wikiSidebar = toStarlightSidebar(parsedNav);
const wikiFirstSlug = firstSlug(parsedNav);

// https://astro.build/config
export default defineConfig({
	output: 'static',
	adapter: cloudflare({ imageService: 'compile' }),
	// No landing page: root redirects to the first synced wiki page. Before the
	// first `sync-wiki` run there is no nav yet, so root is left unmapped (404)
	// rather than pointing at a page that doesn't exist.
	redirects: wikiFirstSlug ? { '/': `/${wikiFirstSlug}/` } : {},
	integrations: [
		starlight({
			title: 'My Docs',
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/withastro/starlight' }],
			sidebar: wikiSidebar,
		}),
	],
});
