// @ts-check
import { existsSync, readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import cloudflare from '@astrojs/cloudflare';

// `src/wiki-nav.json` is generated by `scripts/sync-wiki.mjs` from the wiki's
// `_Sidebar.md` (or an alphabetical fallback). Falls back to the starter
// sidebar when the wiki has never been synced yet.
const navPath = new URL('./src/wiki-nav.json', import.meta.url);
/** @typedef {{label: string, slug: string} | {label: string, items: NavEntry[]}} NavEntry */
/** @param {NavEntry[]} entries @returns {any[]} */
function toStarlightSidebar(entries) {
	return entries.map((entry) =>
		'items' in entry ? { label: entry.label, items: toStarlightSidebar(entry.items) } : entry,
	);
}

/** @type {NavEntry[]} */
const parsedNav = existsSync(navPath) ? JSON.parse(readFileSync(navPath, 'utf-8')) : [];
const wikiSidebar = toStarlightSidebar(parsedNav);

// astro's `defineConfig` doesn't support a `(command) => config` functional
// form (object-only in this version) — detect dev via argv instead.
const isDev = process.argv.slice(2).includes('dev');

// https://astro.build/config
// The Cloudflare adapter routes `astro dev` through workerd's emulated
// runtime, which breaks on Astro's own internal dev-facade bundling. Only
// attach it for build/preview, where it's actually needed.
export default defineConfig({
	output: 'static',
	adapter: isDev ? undefined : cloudflare({ imageService: 'compile' }),
	// No landing page: root redirects to the wiki's Home page.
	redirects: { '/': '/docs/Home/' },
	integrations: [
		starlight({
			title: 'Developer Docs',
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/danjvarela/dev-docs' }],
			sidebar: wikiSidebar,
			head: [
				{
					tag: 'meta',
					attrs: { name: 'robots', content: 'noindex, nofollow' },
				},
			],
		}),
	],
});
