// @ts-check
import { existsSync, readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import cloudflare from '@astrojs/cloudflare';

// `src/wiki-nav.json` is generated by `scripts/sync-wiki.mjs` from the wiki's
// `_Sidebar.md` (or an alphabetical fallback). Falls back to the starter
// sidebar when the wiki has never been synced yet.
const navPath = new URL('./src/wiki-nav.json', import.meta.url);
/** @typedef {{label: string, slug: string} | {label: string, items: NavEntry[]}} NavEntry */
/** @param {NavEntry[]} entries @returns {any[]} */
function toStarlightSidebar(entries) {
	return entries.map((entry) =>
		'items' in entry ? { label: entry.label, items: toStarlightSidebar(entry.items) } : entry,
	);
}

/** @type {NavEntry[]} */
const parsedNav = existsSync(navPath) ? JSON.parse(readFileSync(navPath, 'utf-8')) : [];
const wikiSidebar = existsSync(navPath)
	? toStarlightSidebar(parsedNav)
	: [
			{
				label: 'Guides',
				items: [{ label: 'Example Guide', slug: 'guides/example' }],
			},
			{
				label: 'Reference',
				items: [{ autogenerate: { directory: 'reference' } }],
			},
		];

// https://astro.build/config
export default defineConfig({
	output: 'static',
	adapter: cloudflare({ imageService: 'compile' }),
	integrations: [
		starlight({
			title: 'My Docs',
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/withastro/starlight' }],
			sidebar: wikiSidebar,
		}),
	],
});
